### ISSUE TITLE
How to change card's background color?

### ISSUE THREAD

**Issue by edu1525** [SConaway/react-native-credit-card-display#2]
I need to change that purple color to another one, how can I do it? Thanks!

**Comment by SConaway** [comment]
Hi @edu1525,

Thanks for the issue.

As of now, that's not possible since it comes from the image I'm using. 

I can add additional props to the component to allow you to choose the images used, and then you can either tint them manually or use entirely different images (beware though, other images may not line up correctly). I will do this over the weekend (most likely Saturday) and will push a new build containing that. 

Or, if you prefer, you can make the changes yourself as a PR and I can merge them that way, too. Just let me know if you're doing that so we don't duplicate work.

**Comment by edu1525** [comment]
Ohh cool, I think it will solve my problem, an image with a different color would help-me. Relax, I can wait for the weekend. Thanks!

**Comment by SConaway** [comment]
And...done. Should be available in v0.3.0 now.
